### PR TITLE
Add git and ca-certificates packages to the apt-get install command

### PR DESCRIPTION
**Pull request by sashasimkin**
In order to be able to pull git submodules using `https` I've added git & ca-certificates to installed packages. Also, there's one unnecessary commit with editions to README (it doesn't affect its looking at all).

### CODE REVIEW

**Comment by axilleas** [comment]
@sashasimkin thanks for this, it's requested in GitLab's pages example with Hugo: https://gitlab.com/pages/hugo/issues/1.

Can you update your PR and:
1. Bring README.md to its previous state (not relevant changes with this PR)
2. Squash your commits to only one
3. Provide a proper commit message

?

It's more likely your PR to be accepted if you do these things. Let me know if I can help!

**Comment by sashasimkin** [comment]
Hi! Of course, pushed one more revert commit.
As for squash - you can perform it while accepting PR.
https://github.com/blog/2141-squash-your-commits
I would be glad if you also make a proper commit message. Although I'd name it so:

```
Add `git` and `ca-certificates` to the installed packages in order to be able to pull git submodules using `https`
```

**Comment by axilleas** [comment]
Thanks for the prompt reply!

> As for squash - you can perform it while accepting PR.
> https://github.com/blog/2141-squash-your-commits

Ah yeah, that would work too.

>  I would be glad if you also make a proper commit message. Although I'd name it so:

Not sure what you mean by this, I'm a contributor I don't have write access to this repo :)

**Comment by sashasimkin** [comment]
> Not sure what you mean by this, I'm a contributor I don't have write access to this repo :)

Yeah, sure :) I've confused you with repo owner :) Anyways, it would be helpful for him, and thanks for the tips you've outlined.

**Comment by publysher** [comment]
Hi @sashasimkin 

I am the maintainer :) and I'm wondering about the use case for this PR.

**Comment by sashasimkin** [comment]
@publysher Hi! Please look at the issue @axilleas referring: https://gitlab.com/pages/hugo/issues/1  
In short - it allows usage of git submodules (easier to use existing themes shared as git repos) directly with this image.

**Comment by publysher** [comment]
Themes are a good case IMHO :)

**Comment by axilleas** [comment]
Thank you both!

**Pull request merged**
